name: Build firmware image
run-name: Builds and uploads firmware assets to github

on:
  push:
    branches: ["master"]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi python3
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build firmware image
        run: make magicmouse.bin
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: magicmouse-fw-${{ steps.slug.outputs.sha8 }}
          path: magicmouse.bin

